// <auto-generated />
using System;
using KomisSamochodowy.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KomisSamochodowy.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200429191358_Initial Mysql")]
    partial class InitialMysql
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("KomisSamochodowy.API.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsMain");

                    b.Property<string>("Url");

                    b.Property<int>("ValueId");

                    b.Property<string>("public_id");

                    b.HasKey("Id");

                    b.HasIndex("ValueId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("KomisSamochodowy.API.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<int>("ValueId");

                    b.Property<string>("email");

                    b.Property<DateTime>("sendDate");

                    b.HasKey("Id");

                    b.HasIndex("ValueId");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("KomisSamochodowy.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KomisSamochodowy.API.Models.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EngineCapacity");

                    b.Property<string>("Mark");

                    b.Property<string>("Model");

                    b.Property<string>("color");

                    b.Property<string>("describe");

                    b.Property<string>("fuelType");

                    b.Property<string>("mileage");

                    b.Property<int>("numberOfDoors");

                    b.Property<string>("price");

                    b.Property<string>("year");

                    b.HasKey("Id");

                    b.ToTable("Values");
                });

            modelBuilder.Entity("KomisSamochodowy.API.Models.Photo", b =>
                {
                    b.HasOne("KomisSamochodowy.API.Models.Value", "value")
                        .WithMany("Photos")
                        .HasForeignKey("ValueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KomisSamochodowy.API.Models.Question", b =>
                {
                    b.HasOne("KomisSamochodowy.API.Models.Value", "Value")
                        .WithMany("Questions")
                        .HasForeignKey("ValueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
